"""Insight model for cross-study intelligence engine."""

from pydantic import BaseModel
from typing import Optional


class Insight(BaseModel):
    """Cross-study insight generated by the insights engine."""

    priority: int  # 0 = critical/stage-specific, 1 = cross-study tox, 2 = supporting, 3 = informational
    rule: str  # Rule identifier (e.g., "discrepancy", "cross_species_noael")
    title: str  # Short descriptive title
    detail: str  # Full insight text, 1-3 sentences
    ref_study: Optional[str] = None  # ID of reference study, or null for self-referencing rules
