#!/usr/bin/env python3
"""
audit-knowledge-load-bearing.py — classify every typed fact in
`docs/_internal/knowledge/knowledge-graph.md` by whether it is actually
*consumed* by code, specs, or audits, vs. self-claimed-but-orphaned.

Companion to `audit-knowledge-graph.py` (which enforces internal schema
invariants — confidence, contradicts symmetry, scoring_eligible). This
script answers a different question: "is anyone actually reading this
fact?"

Why this exists: a fact whose `consumed_by[*].status: live` claim points
to a file that no longer mentions the fact_id is silent drift. A fact
with no `consumed_by` and no external grep hits is dead weight. Both
forms erode trust in the knowledge corpus — the user's running complaint
that "files in /knowledge are autogenerated and no one reads them"
generalizes to: facts decay because there is no audit that pairs the
self-claim against the actual codebase.

Per-fact classification (column 1 in the report). Order = pass-strength,
strongest first:

    TEST_VERIFIED        a test file under backend/tests/ or frontend/tests/
                         mentions the fact_id. This is the strongest pass
                         level: a parity test pins the fact's expected
                         behavior in code, so changing the fact's value
                         triggers a test failure. Composes with the
                         validation-harness pattern.
    LIVE_VERIFIED        consumed_by has >=1 live entry AND every claimed
                         file exists AND mentions the fact_id (legacy
                         pattern; weaker than TEST_VERIFIED because the
                         consumer can mention the fact_id in a comment
                         without actually behaving according to it).
    LIVE_OVERCLAIM       consumed_by claims live consumers but one or more
                         either (a) cannot be resolved to a real file or
                         (b) the resolved file does not contain the fact_id
    EXTERNAL_UNDERCLAIM  external grep hits exist that are NOT covered by
                         any consumed_by entry (a real consumer was added
                         without updating the fact's consumer list)
    PLANNED_ONLY         only planned consumed_by, no external hits -- OK,
                         aspirational
    DEAD                 no consumed_by AND no external grep hits -- archive
                         candidate

Run:    python scripts/audit-knowledge-load-bearing.py
Flags:  --write  also writes the markdown report to
                 docs/_internal/knowledge/load-bearing-audit.md
        --strict exit 1 if any fact lands in {LIVE_OVERCLAIM, DEAD}
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from collections import defaultdict
from dataclasses import dataclass, field

try:
    import yaml
except ImportError:
    print("Missing pyyaml. Install: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
GRAPH_PATH = ROOT / "docs/_internal/knowledge/knowledge-graph.md"
REPORT_PATH = ROOT / "docs/_internal/knowledge/load-bearing-audit.md"

# Where to scan for inbound references. Order matters only for reporting.
SEARCH_ROOTS = [
    "backend",          # backend/services + backend/tests
    "frontend/src",
    "frontend/tests",   # property tests cite fact IDs as anchors -- a primary verification surface
    "scripts",
    "docs/_internal/architecture",
    "docs/_internal/research",
    "docs/_internal/incoming",
    "docs/_internal/checklists",
    "docs/_internal/audits",
    "docs/_internal/views",
    "docs/_internal/knowledge",  # Other knowledge files may cite facts.
    ".lattice",
]
EXCLUDE_DIRS = {"node_modules", "venv", ".venv", "_archived", "archive", "__pycache__", ".git", "dist", "build"}
EXCLUDE_NAMES = {"knowledge-graph.md"}  # The fact's own home doesn't count as an inbound reference.

# Match all fact_id forms present today plus any future <PREFIX>-FACT-<n>[<letter>].
FACT_ID_RE = re.compile(r"\b([A-Z][A-Z0-9]*-FACT-\d+[a-z]?)\b")


@dataclass
class FactClaim:
    fact_id: str
    consumed_by: list[dict] = field(default_factory=list)  # raw consumed_by entries
    yaml_block_present: bool = False


@dataclass
class FactReport:
    fact_id: str
    classification: str
    live_count: int
    planned_count: int
    external_hits: list[Path]
    overclaim_paths: list[str]
    underclaim_files: list[Path]
    test_files: list[Path] = field(default_factory=list)


def parse_facts(graph_md: str) -> dict[str, FactClaim]:
    """Extract fact_id + consumed_by from each ```yaml block in knowledge-graph.md."""
    facts: dict[str, FactClaim] = {}
    # Each fact starts with `id: <FACT-ID>` inside a ```yaml fence. Grab fence-by-fence.
    fence_re = re.compile(r"```yaml\s*\n(.*?)```", re.DOTALL)
    for match in fence_re.finditer(graph_md):
        block = match.group(1)
        try:
            data = yaml.safe_load(block)
        except yaml.YAMLError:
            continue
        if not isinstance(data, dict):
            continue
        fid = data.get("id")
        if not fid or not isinstance(fid, str) or "-FACT-" not in fid:
            continue
        consumed = data.get("consumed_by") or []
        if not isinstance(consumed, list):
            consumed = []
        facts[fid] = FactClaim(fact_id=fid, consumed_by=consumed, yaml_block_present=True)
    return facts


def file_iter(roots: list[Path]):
    """Yield every text-file path under the search roots, excluding excluded dirs."""
    text_exts = {".py", ".ts", ".tsx", ".js", ".jsx", ".md", ".yaml", ".yml", ".sql", ".sh", ".json", ".txt"}
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if path.suffix not in text_exts:
                continue
            if any(part in EXCLUDE_DIRS for part in path.parts):
                continue
            if path.name in EXCLUDE_NAMES:
                continue
            yield path


def scan_external_hits(facts: dict[str, FactClaim]) -> dict[str, set[Path]]:
    """Walk the codebase once; record which files mention each fact_id."""
    hits: dict[str, set[Path]] = defaultdict(set)
    fact_ids = set(facts.keys())
    if not fact_ids:
        return hits
    roots = [ROOT / r for r in SEARCH_ROOTS]
    for path in file_iter(roots):
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for fid in FACT_ID_RE.findall(text):
            if fid in fact_ids:
                hits[fid].add(path)
    return hits


def extract_path_from_claim(claim_path: str) -> str | None:
    """`backend/services/analysis/hcd.py:assess_a3_lb -- desc` -> `backend/services/analysis/hcd.py`.
    Returns None for shapes that don't look like file paths (e.g. SQLite row claims)."""
    head = claim_path.split(" -- ", 1)[0].strip()
    head = head.split(":", 1)[0].strip()
    if not head:
        return None
    if head.endswith(".sqlite") or "sqlite" in head.lower():
        return None  # SQLite row claims aren't file mentions; skip.
    if "/" not in head and "\\" not in head:
        return None
    return head


def classify(claim: FactClaim, hits: set[Path]) -> FactReport:
    live = [c for c in claim.consumed_by if c.get("status") == "live"]
    planned = [c for c in claim.consumed_by if c.get("status") == "planned"]
    overclaim_paths: list[str] = []

    for entry in live:
        raw = entry.get("path") or ""
        rel = extract_path_from_claim(raw)
        if rel is None:
            continue  # Non-file claim (sqlite row, narrative); skip path verification.
        # Claim convention is inconsistent: some claims are repo-root-relative
        # (`backend/services/analysis/hcd.py`), others are docs-internal-relative
        # (`research/literature/<slug>.md`). Try repo-root first, fall back to
        # docs/_internal/. Don't flag inconsistent convention here -- that's an
        # audit-knowledge-graph.py concern; this script just resolves the claim.
        candidates = [ROOT / rel, ROOT / "docs/_internal" / rel]
        full = next((c for c in candidates if c.exists()), None)
        if full is None:
            overclaim_paths.append(f"{rel} [missing file]")
            continue
        try:
            text = full.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            overclaim_paths.append(f"{rel} [unreadable]")
            continue
        if claim.fact_id not in text:
            overclaim_paths.append(f"{rel} [no fact_id mention]")

    # Underclaim: external grep hit that isn't covered by ANY claim path
    # (live or planned). We only need a coarse cover-check here — full path
    # match is brittle because claims often carry suffixes (`:func -- desc`).
    claim_substrings: list[str] = []
    for entry in claim.consumed_by:
        rel = extract_path_from_claim(entry.get("path") or "")
        if rel:
            claim_substrings.append(rel.replace("\\", "/"))
    underclaim_files: list[Path] = []
    for hit in sorted(hits):
        rel_hit = str(hit.relative_to(ROOT)).replace("\\", "/")
        if not any(sub in rel_hit for sub in claim_substrings):
            underclaim_files.append(hit)

    # Test-file consumers: the strongest pass-level. Any file under */tests/
    # that mentions the fact_id is a parity test (or at least a behavioral
    # reference). Treated as the primary verification path.
    test_files = sorted(h for h in hits if "/tests/" in str(h).replace("\\", "/"))

    if test_files:
        cls = "TEST_VERIFIED"
    elif overclaim_paths:
        cls = "LIVE_OVERCLAIM"
    elif live:
        cls = "LIVE_VERIFIED"
    elif underclaim_files:
        cls = "EXTERNAL_UNDERCLAIM"
    elif planned:
        cls = "PLANNED_ONLY"
    elif not hits:
        cls = "DEAD"
    else:
        # Defensive: hits exist but no consumed_by AND no overclaim — treat as underclaim.
        cls = "EXTERNAL_UNDERCLAIM"

    return FactReport(
        fact_id=claim.fact_id,
        classification=cls,
        live_count=len(live),
        planned_count=len(planned),
        external_hits=sorted(hits),
        overclaim_paths=overclaim_paths,
        underclaim_files=underclaim_files,
        test_files=test_files,
    )


def render_report(reports: list[FactReport]) -> str:
    by_class: dict[str, list[FactReport]] = defaultdict(list)
    for r in reports:
        by_class[r.classification].append(r)

    lines: list[str] = []
    lines.append("# Knowledge Graph -- Load-Bearing Audit")
    lines.append("")
    lines.append("Auto-generated by `scripts/audit-knowledge-load-bearing.py`. Pairs each typed fact's `consumed_by` self-claim against actual grep hits in the codebase. Defects (LIVE_OVERCLAIM, DEAD) are silent-drift surface.")
    lines.append("")
    total = len(reports)
    lines.append(f"**Facts audited:** {total}")
    for cls in ["TEST_VERIFIED", "LIVE_VERIFIED", "LIVE_OVERCLAIM", "EXTERNAL_UNDERCLAIM", "PLANNED_ONLY", "DEAD"]:
        n = len(by_class.get(cls, []))
        lines.append(f"- {cls}: {n}")
    lines.append("")

    for cls in ["LIVE_OVERCLAIM", "DEAD", "EXTERNAL_UNDERCLAIM", "PLANNED_ONLY", "LIVE_VERIFIED", "TEST_VERIFIED"]:
        bucket = by_class.get(cls, [])
        if not bucket:
            continue
        lines.append(f"## {cls} ({len(bucket)})")
        lines.append("")
        for r in bucket:
            lines.append(f"### {r.fact_id}")
            lines.append("")
            lines.append(f"- live claims: {r.live_count} / planned claims: {r.planned_count} / external hits: {len(r.external_hits)} / test files: {len(r.test_files)}")
            if r.test_files:
                lines.append(f"- **Verifying tests:**")
                for p in r.test_files:
                    lines.append(f"    - {p.relative_to(ROOT)}")
            if r.overclaim_paths:
                lines.append(f"- **Overclaimed paths:**")
                for p in r.overclaim_paths:
                    lines.append(f"    - {p}")
            if r.underclaim_files:
                # Cap display at 10 files per fact; full set is in the script run.
                shown = r.underclaim_files[:10]
                lines.append(f"- **Underclaimed external hits ({len(r.underclaim_files)}):**")
                for p in shown:
                    rel = p.relative_to(ROOT)
                    lines.append(f"    - {rel}")
                if len(r.underclaim_files) > 10:
                    lines.append(f"    - ... and {len(r.underclaim_files) - 10} more")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true", help="write report to docs/_internal/knowledge/load-bearing-audit.md")
    parser.add_argument("--strict", action="store_true", help="exit 1 if any fact is LIVE_OVERCLAIM, DEAD, or has no TEST_VERIFIED status")
    args = parser.parse_args(argv)

    if not GRAPH_PATH.exists():
        print(f"knowledge-graph.md not found at {GRAPH_PATH}", file=sys.stderr)
        return 2

    facts = parse_facts(GRAPH_PATH.read_text(encoding="utf-8"))
    if not facts:
        print("No facts found in knowledge-graph.md (parse failure?)", file=sys.stderr)
        return 2

    hits = scan_external_hits(facts)
    reports = [classify(claim, hits.get(fid, set())) for fid, claim in facts.items()]
    reports.sort(key=lambda r: (r.classification, r.fact_id))

    out = render_report(reports)
    print(out)
    if args.write:
        REPORT_PATH.write_text(out, encoding="utf-8")
        print(f"\nWrote {REPORT_PATH.relative_to(ROOT)}", file=sys.stderr)

    if args.strict:
        bad = [r for r in reports if r.classification in {"LIVE_OVERCLAIM", "DEAD"}]
        if bad:
            print(f"\nstrict: {len(bad)} fact(s) failed (LIVE_OVERCLAIM or DEAD).", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
